using System.Text;

namespace Community.VisualStudio.SourceGenerators;

public abstract class GeneratorBase
{
    private protected static void WritePreamble(StringBuilder builder)
    {
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine();
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
    }

    private protected static void WriteClassStart(StringBuilder builder, string namespaceName, string summaryDocumentation, string className)
    {
        builder.AppendLine($"namespace {namespaceName}");
        builder.AppendLine("{");
        builder.AppendLine($"    /// <summary>{summaryDocumentation}</summary>");
        builder.AppendLine($"    internal sealed partial class {className}");
        builder.AppendLine("    {");
    }

    private protected static void WriteClassEnd(StringBuilder builder)
    {
        builder.AppendLine("    }");
        builder.AppendLine("}");
    }
}
