//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.VisualStudio.SourceGenerators {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Community.VisualStudio.SourceGenerators.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project does not contain a &apos;source.extension.vsixmanifest&apos; file.
        /// </summary>
        internal static string CVSSG001_MessageFormat {
            get {
                return ResourceManager.GetString("CVSSG001_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project should contain a VSIX manifest file.
        /// </summary>
        internal static string CVSSG001_Title {
            get {
                return ResourceManager.GetString("CVSSG001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;source.extension.vsixmanifest&apos; file is invalid: {0}.
        /// </summary>
        internal static string CVSSG002_MessageFormat {
            get {
                return ResourceManager.GetString("CVSSG002_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VSIX manifest file should be valid.
        /// </summary>
        internal static string CVSSG002_Title {
            get {
                return ResourceManager.GetString("CVSSG002_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project does not have a root namespace and a namespace was not specified against the AdditionalFiles item for {0}.
        /// </summary>
        internal static string CVSSG003_MessageFormat {
            get {
                return ResourceManager.GetString("CVSSG003_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace must be specified for generated code.
        /// </summary>
        internal static string CVSSG003_Title {
            get {
                return ResourceManager.GetString("CVSSG003_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command table file &apos;{0}&apos; is invalid: {1}.
        /// </summary>
        internal static string CVSSG004_MessageFormat {
            get {
                return ResourceManager.GetString("CVSSG004_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command table file shuld be valid.
        /// </summary>
        internal static string CVSSG004_Title {
            get {
                return ResourceManager.GetString("CVSSG004_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The symbol &apos;{0}&apos; is defined multiple times with different values.
        /// </summary>
        internal static string CVSSG005_MessageFormat {
            get {
                return ResourceManager.GetString("CVSSG005_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbols in command tables should be unique.
        /// </summary>
        internal static string CVSSG005_Title {
            get {
                return ResourceManager.GetString("CVSSG005_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The manifest file could not be parsed. {0}.
        /// </summary>
        internal static string Error_CouldNotParseManifest {
            get {
                return ResourceManager.GetString("Error_CouldNotParseManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GuidSymbol named &apos;{0}&apos; cannot be parsed as a GUID..
        /// </summary>
        internal static string Error_InvalidGuidSymbol {
            get {
                return ResourceManager.GetString("Error_InvalidGuidSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IDSymbol named &apos;{0}&apos; cannot be parsed as a hexadecimal number..
        /// </summary>
        internal static string Error_InvalidIdSymbol {
            get {
                return ResourceManager.GetString("Error_InvalidIdSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the XML node &apos;{0}&apos; in the vsixmanifest file..
        /// </summary>
        internal static string Error_ManifestNodeNotFound {
            get {
                return ResourceManager.GetString("Error_ManifestNodeNotFound", resourceCulture);
            }
        }
    }
}
