using System.Text;

namespace Community.VisualStudio.SourceGenerators;

internal abstract class WriterBase
{
    private static readonly Version _nullableReferenceMinVersion = new(8, 0);

    private protected static void WritePreamble(StringBuilder builder, string langVersion)
    {
        builder.AppendLine("// <auto-generated/>");
        if (CanUseNullableReferences(langVersion))
        {
            builder.AppendLine();
            builder.AppendLine("#nullable enable");
        }
        builder.AppendLine();
    }

    private static bool CanUseNullableReferences(string langVersion)
    {
        if (string.Equals(langVersion, "latest", StringComparison.OrdinalIgnoreCase))
        {
            // Assume the latest version supports nullable references.
            return true;
        }

        if (Version.TryParse(langVersion, out Version version))
        {
            return version > _nullableReferenceMinVersion;
        }

        return false;
    }
}
